### ISSUE TITLE
Not Participating in Hacktober Fest

### ISSUE THREAD

**Issue by SoyebSarkar** [codemistic/Data-Structures-and-Algorithms#17]
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/96381266/193397820-6114c050-d494-4be7-b401-45efe959b649.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/96381266/193397843-bb34746f-5eae-4420-8984-73ff99002ddc.png">
Hello admin, why this pr is not under Hacktoberfest?
It's Showing not accepting for this project

**Comment by gantavyamalviya** [comment]
Check Now!

**Comment by SoyebSarkar** [comment]
@gantavyamalviya 
Thank You, now it's updated
<img width="460" alt="image" src="https://user-images.githubusercontent.com/96381266/193399616-b6d54f40-551b-4d82-ad1b-2ac6e82ecafb.png">
