### ISSUE TITLE
create a folder of leetcode question

### ISSUE THREAD

**Issue by tamannasgh** [codemistic/Data-Structures-and-Algorithms#260]
in the leetcode folder there will be three folders easy, medium and hard and people can contribute there solution and question link according to level

**Comment by Tamanna-S** [comment]
may i work on this i have some nice binary search questions!

**Comment by shreya2004-26** [comment]
I would like to add some amaazing leetcode DSA problems which i have gone through.
Will you please assign me this task?

**Comment by shreya2004-26** [comment]
1) Find peak index in a mountain array
2) Find unique number of occurrences in an array
3) Find pivot in an array
4) Find duplicates in an array

**Comment by Tamanna-S** [comment]
may you check this out 
added leetcode-solution folder #442
