### ISSUE TITLE
Which challenges are we supposed to implement solutions for?

### ISSUE THREAD

**Issue by Itsfoss0** [codemistic/Data-Structures-and-Algorithms#27]
Hello,
I  want to contribute to  the python Data structures and Algorithms. I don't however know  which challenges I'm supposed to write solutions for. Are  we to contribute solutions  strictly to [Leet code](https://leetcode.com/) challenges or any DSA related challenge?
Thanks.

**Comment by gantavyamalviya** [comment]
You can contribute any DSA related challenge/problem.

**Comment by Itsfoss0** [comment]
Ok, 
Thanks.
