### ISSUE TITLE
Operations on arrays

### ISSUE THREAD

**Issue by ola-nishant** [codemistic/Data-Structures-and-Algorithms#464]
I want to create a program in cpp which is totally menu driven, and has all the operations like sort, searching, etc
please assign it to me and add the hacktoberfest label

**Comment by ggautamgoyalg** [comment]
Hey! Shall i work on this issue?

**Comment by meenal0205** [comment]
I would like to work on this please assign this to me

**Comment by ig77ayush** [comment]
Please assign this issue to me
