### ISSUE TITLE
Please remove Hacktoberfest tag from this repo ( Project excluded from hacktoberfest )

### ISSUE THREAD

**Issue by iamrahul8** [codemistic/Data-Structures-and-Algorithms#697]
![image](https://user-images.githubusercontent.com/72541381/194347122-ea3ab5b0-76ea-4704-9aa4-0415937cb20a.png)
@gantavyamalviya

**Comment by thekalyan001** [comment]
yes why this issue is there?

**Comment by iamrahul8** [comment]
> yes why this issue is there?

@thekalyan001 , this repo is excluded from hacktoberfest , and still have hacktoberfest tag attached which is making confusion.
